drop database if exists entidades;
create database entidades;
use entidades;
CREATE TABLE CLIENTE(
	IDCLIENTE 	int PRIMARY KEY AUTO_INCREMENT,
	NOMBRE		VARCHAR(50) NOT NULL,
	DIRECCION	VARCHAR(50) NOT NULL
);
CREATE TABLE FACTURA(
	FACTURAID	int	PRIMARY KEY AUTO_INCREMENT NOT NULL,
	MONTO		int	NOT NULL
);
CREATE TABLE VEHICULO(
	VEHICULOID	int	PRIMARY KEY AUTO_INCREMENT NOT NULL,
	PLACA		int	NOT NULL,
	MARCA		VARCHAR(20)	NOT NULL,
	MODELO		VARCHAR(20)	NOT NULL,
	FACTURAID	int	NOT NULL,
	FOREIGN KEY (FACTURAID) REFERENCES FACTURA(FACTURAID)
);
CREATE TABLE POLIZA(
	POLIZAID	INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	COSTO		FLOAT NOT NULL,
	PRIMA 		FLOAT NOT NULL,
	FECHA_AP	DATE NOT NULL,
	FECHA_VEN	DATE NOT NULL,
	IDCLIENTE	INT NOT NULL,
	VEHICULOID	INT NOT NULL,
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
	FOREIGN KEY (VEHICULOID) REFERENCES VEHICULO(VEHICULOID)
);
